#!/usr/bin/env bash
# configures an nginx server to listen on port 80.

# remove the default nginx configuration file 
rm /etc/nginx/sites-enabled/default
# configure ngnix to listen to port 80 for all active Ipv4 Ips
ln -s/etc/nginx/sites-available/default/etc/nginx/sites-enabled/default
# restart the nginx
service ngnix restart
